### ISSUE TITLE
Separate the model from the web application

### ISSUE THREAD

**Issue by mohamedramadan2515** [tarek-nawara/sentiment-analysis#17]
every time we need to run the web application and stream tweets, we also need to train the model first.

**Comment by tarek-nawara** [comment]
Good point, we can save the model after training it offline and then read it in the application start

**Comment by tarek-nawara** [comment]
the simplest way is to follow this  [link](https://databricks.com/blog/2016/05/31/apache-spark-2-0-preview-machine-learning-model-persistence.html).

**Comment by MohamedElhawaty** [comment]
Both the models that we are working with support saving and loading a trained model. I have implemented the following in the deeplearning branch, If the model is already trained and saved in a specified directory, the builder class will load it directly, otherwise, the builder will train the model and save it.
